### PR TITLE
Add SkyMart shop

### PR DESCRIPTION
**Pull request by heyngra**
required by https://github.com/NotEnoughUpdates/NotEnoughUpdates/pull/756

### CODE REVIEW

**Review by jani270 — CHANGES_REQUESTED** [review]
What is the reason for `isWorthless` and `display`? Cant you get the display by looking for the normal file in the repo?

**Comment by heyngra** [comment]
> What is the reason for `isWorthless` and `display`? Cant you get the display by looking for the normal file in the repo?

`isWorthless`: I don't know it's the appropriate name (it wasn't commented before), but it references items in SkyMart, that are rather useless, such as basic hoes that give you +5 farming fortune (and probably no one will buy them off ah), or Builder's Ruler, where the same thing applies

`display`: in SkyMart shops there are books such as Sunder I. Showing to the player, that someone will get 5k coins for selling `Enchanted Book` is a pretty unhelpful tip, looking at various books in the shop. At least in the editor, the display name is just `§fEnchanted Book` which showing to the player wouldn't be helpful. Maybe there is a way to get the book enchantment name as a display name, while getting normal items display names with the same way, but I didn't really work much with the repo, so idk.
image

**Comment by jani270** [comment]
> > What is the reason for `isWorthless` and `display`? Cant you get the display by looking for the normal file in the repo?
> 
> `isWorthless`: I don't know it's the appropriate name (it wasn't commented before), but it references items in SkyMart, that are rather useless, such as basic hoes that give you +5 farming fortune (and probably no one will buy them off ah), or Builder's Ruler, where the same thing applies
> 
> `display`: in SkyMart shops there are books such as Sunder I. Showing to the player, that someone will get 5k coins for selling `Enchanted Book` is a pretty unhelpful tip, looking at various books in the shop. At least in the editor, the display name is just `§fEnchanted Book` which showing to the player wouldn't be helpful. Maybe there is a way to get the book enchantment name as a display name, while getting normal items display names with the same way, but I didn't really work much with the repo, so idk. image

I dont think the isWorthless field is good to put in the repo as it is not really our decisions, its just another thing we have to update if hypixel decides to change smth on these items.

**Comment by heyngra** [comment]
> 



> > > What is the reason for `isWorthless` and `display`? Cant you get the display by looking for the normal file in the repo?
> > 
> > 
> > `isWorthless`: I don't know it's the appropriate name (it wasn't commented before), but it references items in SkyMart, that are rather useless, such as basic hoes that give you +5 farming fortune (and probably no one will buy them off ah), or Builder's Ruler, where the same thing applies
> > `display`: in SkyMart shops there are books such as Sunder I. Showing to the player, that someone will get 5k coins for selling `Enchanted Book` is a pretty unhelpful tip, looking at various books in the shop. At least in the editor, the display name is just `§fEnchanted Book` which showing to the player wouldn't be helpful. Maybe there is a way to get the book enchantment name as a display name, while getting normal items display names with the same way, but I didn't really work much with the repo, so idk. image
> 
> I dont think the isWorthless field is good to put in the repo as it is not really our decision if an item is worth or not, its just another thing we have to update if hypixel decides to change smth on these items.

what would you think about changing it to `isTool` or something like this? it would filter out all items that are `isWorthless` either way cuz the list of "worthless" items consists of hoes, axes, cleaning scythes and builder's rules, which all of them can be classified as a tool?
or maybe another way: adding a type to each item, and classifiying them as mentioned before as tool, skin, equipment, enchant ,fuel (for the biofuel one), reforge

**Comment by jani270** [comment]
> > 
> 
> > > > What is the reason for `isWorthless` and `display`? Cant you get the display by looking for the normal file in the repo?
> > > 
> > > 
> > > `isWorthless`: I don't know it's the appropriate name (it wasn't commented before), but it references items in SkyMart, that are rather useless, such as basic hoes that give you +5 farming fortune (and probably no one will buy them off ah), or Builder's Ruler, where the same thing applies
> > > `display`: in SkyMart shops there are books such as Sunder I. Showing to the player, that someone will get 5k coins for selling `Enchanted Book` is a pretty unhelpful tip, looking at various books in the shop. At least in the editor, the display name is just `§fEnchanted Book` which showing to the player wouldn't be helpful. Maybe there is a way to get the book enchantment name as a display name, while getting normal items display names with the same way, but I didn't really work much with the repo, so idk. image
> > 
> > 
> > I dont think the isWorthless field is good to put in the repo as it is not really our decision if an item is worth or not, its just another thing we have to update if hypixel decides to change smth on these items.
> 
> what would you think about changing it to `isTool` or something like this? it would filter out all items that are `isWorthless` either way cuz the list of "worthless" items consists of hoes, axes, cleaning scythes and builder's rules, which all of them can be classified as a tool? or maybe another way: adding a type to each item, and classifiying them as mentioned before as tool, skin, equipment, enchant ,fuel (for the biofuel one), reforge

I would just make option to filter items that are under a certain price per copper, then the user has the option and we are out of that.

**Comment by CalMWolfs** [comment]
>  At least in the editor, the display name is just `§fEnchanted Book` which showing to the player wouldn't be helpful. Maybe there is a way to get the book enchantment name as a display name, while getting normal items display names with the same way, but I didn't really work much with the repo, so idk. 

It seems you have already fixed the other problems but if Jani still doesn't want the display field in the repo you could look at how SkyHanni gets the name of an enchanted book through using internal name. The function is in this file
https://github.com/hannibal002/SkyHanni/blob/beta/src/main/java/at/hannibal2/skyhanni/utils/ItemUtils.kt

**Review by jani270 — APPROVED** [review]
Still not a big fan but ig

**Review by Lulonaut — APPROVED** [review]

**Pull request merged**
