### PR TITLE
Fix: Update Day/Night Saver lore

### PR DESCRIPTION
**Pull request by martimavocado**

### CODE REVIEW

**Comment by CalMWolfs** [comment]
Should be into master afaik and then the action will also say there are problems becasue you didnt change the nbt.
Instead of manually changing the text you should use edit mode like it says in the readme

**Comment by martimavocado** [comment]
saw this one was more updated and game complained when trying to use master, ty for pointing out nbt

**Comment by CalMWolfs** [comment]
> game complained when trying to use master

game uses prerelease but master gets merged into it and prs go into master

**Comment by martimavocado** [comment]
time for a 3rd pr then

**Pull request closed without merging**
