### PR TITLE
Remove count from recipe

### PR DESCRIPTION
**Pull request by Ekwav**
This commit introduced two count properties for no apparent reason.
https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/commit/5cdcc154ce9ff34ec213b9b7cc788d4e18657b3e#diff-65e468c8bfcb940e7625b2684e40472f4a2dfa859a559e906568ac28846b35dbR30

It broke my parsing and I don't see why it was added so I assume it was a mistake.

This PR removes the count values in the crafting recipe again.

### CODE REVIEW

**Comment by NopoTheGamer** [comment]
the count is how many you get, 1. how did it break your parsing 2. im sure its going to be used soon

**Comment by Ekwav** [comment]
Thanks, also just saw it in the wiki.
The parsing is a Dictionary<string,string> to iterate over the required ingredients (can't parse numbers). And the count isn't an ingredient so I didn't think that it would be the result amount. Baits also commonly have more resulting items. 
Alright, then I will have to update it on my end.

**Comment by romangraef** [comment]
Hiii @Ekwav  can i advertise https://github.com/NotEnoughUpdates/RepoParser/ rq? Maybe it already has what you need

**Comment by Ekwav** [comment]
> Hiii @Ekwav can i advertise https://github.com/NotEnoughUpdates/RepoParser/ rq? Maybe it already has what you need

thanks @romangraef but my stack is build on dotnet so a java based parser is not of use to me.
My old data model just didn't support an int in the recipe and I didn't get the connection from the property name `count` to the `craftResultCount`. So I thought it was added by mistake.

**Pull request closed without merging**
