### PR TITLE
atom

### PR DESCRIPTION
**Pull request by jani270**
This pr includes #725 as the person dosent fix their annotations

### CODE REVIEW

**Review by NopoTheGamer — DISMISSED** [review]
"itemid": "minecraft::skull:",

**Review by NopoTheGamer — APPROVED** [review]
jani270 dismissed NopoTheGamer’s stale review via c614b1f :skull:

**Review by NopoTheGamer — APPROVED** [review]
This item can't be reforged!

**Review by exhq — APPROVED** [review]
im too lazy to check the rest

**Review by Lulonaut — APPROVED** [review]

**Pull request merged**
