### PR TITLE
Rusty Stuff

### PR DESCRIPTION
**Pull request by SchIaumeyer**
- One Item is missing, it's the new travel scroll

### CODE REVIEW

**Comment by SchIaumeyer** [comment]
...

**Comment by jani270** [comment]
lmao

**Comment by jani270** [comment]
I've detected some problems you might want to take a look at, you can see them as annotations in the files tab.

**Review by Lulonaut — APPROVED** [review]

**Review by jani270 — APPROVED** [review]
I've detected some problems you might want to take a look at, you can see them as annotations in the files tab.

**Pull request merged**
