### PR TITLE
General nbt updates

### PR DESCRIPTION
**Pull request by Eejit43**

### CODE REVIEW

**Comment by Eejit43** [comment]
Note on the AttributeModifiers one (I mistyped that). I have only found that tag in GUIs _or_ on modified items. I'm not sure why it is there, but I don't think it does anything as a blank string. Please correct me if I'm wrong!

**Comment by Eejit43** [comment]
About the originTags, I personally think those should be removed. If you look at the recipes of items and such like that, they don't have that originTag. However, I guess that could be useful if you are looking at the NBT. I don't have too strong of an opinion on that.

**Comment by jani270** [comment]
I dont see a point in merging this

**Comment by Eejit43** [comment]
Well they don't _need_ to be done, but it is technically what they actually are. Anyway the modifiers removal should definitely be done. I don't see the harm in merging this.

**Comment by Eejit43** [comment]
Does anyone have anything to add to this? I can revert some of these changes if you think I shouldn't have made them, but I think they make sense.

**Comment by Eejit43** [comment]
Seems like this won't be merged, closing

**Pull request closed without merging**
