### PR TITLE
add gemstone slot unlock costs

### PR DESCRIPTION
**Pull request by Fix3dll**
Similar format to essencecosts.json

### CODE REVIEW

**Comment by kr45732** [comment]
Aren't these all already in /resources/skyblock/items?

**Comment by romangraef** [comment]
> Aren't these all already in /resources/skyblock/items?

I mean we are trying to cut down on api requests, even public endpoints.

**Comment by Fix3dll** [comment]
Python script for keeps up to date gemstonecosts.json:  https://gist.github.com/Fix3dll/3963c049e068a3dc5312c4930ce5c938

**Comment by hannibal002** [comment]
I mean we are trying to cut down on api requests, even public endpoints.

Will we add NPC prices to item repo too now? @romangraef 

Fetching the whole item list once per game start doesn't hurt hypixel

**Review by jani270 — APPROVED** [review]

**Review by NopoTheGamer — APPROVED** [review]

**Pull request merged**
