### PR TITLE
Terrible pet nbts

### PR DESCRIPTION
**Pull request by romangraef**
This is currently auto generated and (as you can tell by the diff) does not preserve the ordering of the original json. I am unsure if i want to fix this (which would ideally be fixed by introducing some canonical ordering of the json keys, perhaps alphabetically), or if i just want to delegate that work to the cheap, affordable human labor hours of @jani270.

### CODE REVIEW

**Comment by romangraef** [comment]
Currently the keys are sorted alphabetically in this PR, but obviously this isnt the standard of the surrounding repo.

**Comment by jani270** [comment]
ahhhhhh why

**Comment by jani270** [comment]
Also shouldnt this go to prerelease instead of master?

**Comment by romangraef** [comment]
> ahhhhhh why

Well, if you can give me a consistent ordering of the json keys i can use that.

**Pull request merged**
