### PR TITLE
Add forge recipes

### PR DESCRIPTION
**Pull request by ENORMOUZ**

### CODE REVIEW

**Comment by ENORMOUZ** [comment]
Oh, lemme check those, thanks

**Comment by DeDiamondPro** [comment]
I personally liked the idea of having it be in a forgerecipe field more (like you did originally) because it doesn't really make sense that the recipe is in the crafting tab thingy tbh (especially for coins) and it would be cool if we could create a new ui for it. (don't go ahead changing everything because of things I said I would wait for Jani or Iron to give clarification)

**Comment by IRONM00N** [comment]
> I personally liked the idea of having it be in a forgerecipe field more (like you did originally) because it doesn't really make sense that the recipe is in the crafting tab thingy tbh (especially for coins) and it would be cool if we could create a new ui for it. (don't go ahead changing everything because of things I said I would wait for Jani or Iron to give clarification)

I agree with what you said

**Comment by ENORMOUZ** [comment]
Hmm but yeah it will take some coding, should we add it as raw cost for the moment and add custom GUI next time?

**Comment by jani270** [comment]
Closing due to a implementation in a another way,

**Comment by ENORMOUZ** [comment]
> Closing due to a implementation in a another way,

May I know which pull request this was added in? Would like to see how it was implemented

**Comment by romangraef** [comment]
@ENORMOUZ https://github.com/NotEnoughUpdates/NotEnoughUpdates/pull/40 and https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/pull/660

**Pull request closed without merging**
