### PR TITLE
Random recipes

### PR DESCRIPTION
**Pull request by MrChuw**
If there are any mistakes I'm sorry, I just proofread about 3000 to 4000 wiki pages.

### CODE REVIEW

**Comment by MrChuw** [comment]
I don't know where I can get the item's ntbtag to check.

**Comment by Ascynx** [comment]
image
just replace the 580 in the nbt tag for a 750 and it should stop screaming at you

**Review by jani270 — COMMENTED** [review]
Most of your changes have a random space behind the modver is there a reason why?

**Comment by MrChuw** [comment]
> Most of your changes have a random space behind the modver is there a reason why?

Yes, because I have a habit of putting a space at the end, and I ended up forgetting to delete it before uploading.

**Review by jani270 — APPROVED** [review]

**Review by Lulonaut — APPROVED** [review]

**Pull request merged**
