### PR TITLE
add eman slayer requirements

### LINKED ISSUE #760: Enderman slayer is missing
The slayer_req is missing for items from the enderman slayer. 
Should it be EMAN_X or ENDERMAN_X (I intend to make a PR later today)

### PR DESCRIPTION
**Pull request by Ekwav**
Adds enderman slayer requirements for item crafting based on https://hypixel-skyblock.fandom.com/wiki/Enderman_Slayer#VII
fixes #760

### CODE REVIEW

**Comment by Ekwav** [comment]
> This pr is unfortunately useless as neu dosent even use this "req" thing anymore

What does it instead?

**Comment by jani270** [comment]
> > This pr is unfortunately useless as neu dosent even use this "req" thing anymore
> 
> What does it instead?

This was only for the collection log feature which got removed a long long time ago

**Comment by Ekwav** [comment]
> > > This pr is unfortunately useless as neu dosent even use this "req" thing anymore
> > 
> > 
> > What does it instead?
> 
> This was only for the collection log feature which got removed a long long time ago

Okay, should I close the PR then?
I display the slayer requirement on https://sky.coflnet.com/crafts gonna use my fork as source instead of this repository then.

**Comment by jani270** [comment]
> > > > This pr is unfortunately useless as neu dosent even use this "req" thing anymore
> > > 
> > > 
> > > What does it instead?
> > 
> > 
> > This was only for the collection log feature which got removed a long long time ago
> 
> Okay, should I close the PR? I display the slayer requirement on https://sky.coflnet.com/crafts gonna use my fork as source instead of this repository then.

Sorry for the late reply, its fine we will merge it as it dosent really hurt us and its easier for you as you dont need to update your fork everytime we make changes :)

**Review by jani270 — APPROVED** [review]

**Review by Lulonaut — APPROVED** [review]

**Pull request merged**
