### PR TITLE
museum changes

### PR DESCRIPTION
**Pull request by 7azeemm**
fixed few sets had wrong pieces
removed dungeon heads / hats from rarities
added armor_names

### CODE REVIEW

**Comment by CalMWolfs** [comment]
Hey so we generate this file automatically, good catch on there being some items in special that are already in another category, ive made a fix for this in #1461 
As for the changes to the armor sets, as ive said, we get this data from the hypixel api and it seems that some of that is incorrect.
```
Blaze armor -> hypixel says it has blaze belt in the api but it doesn’t
Crimson hunter set -> hypixel says it has blaze armor but it doesn’t
End set -> hypixel added the rest of the equipment later so I guess it never got added to the set in the api
Monster raider -> hypixel wrongly still includes the spider boots in the set
Snow set -> same thing, equipment added later so not changed in api
Sponge set -> hypixel api says the whole fisherman set is also needed in that which is wrong
```

As for the armor_names, what is this used for? As we already have a way to convert the item stack name that hypixel shows in the museum gui to the museum set name. See here: https://github.com/NotEnoughUpdates/NotEnoughUpdates/blob/f4df7d2b6a4479415e879de8620740ae4471ed27/src/main/kotlin/io/github/moulberry/notenoughupdates/util/MuseumUtil.kt#L92

**Comment by DuckySoLucky** [comment]
> Hey so we generate this file automatically, good catch on there being some items in special that are already in another category, ive made a fix for this in #1461 As for the changes to the armor sets, as ive said, we get this data from the hypixel api and it seems that some of that is incorrect.
> 
> ```
> Blaze armor -> hypixel says it has blaze belt in the api but it doesn’t
> Crimson hunter set -> hypixel says it has blaze armor but it doesn’t
> End set -> hypixel added the rest of the equipment later so I guess it never got added to the set in the api
> Monster raider -> hypixel wrongly still includes the spider boots in the set
> Snow set -> same thing, equipment added later so not changed in api
> Sponge set -> hypixel api says the whole fisherman set is also needed in that which is wrong
> ```
> 
> As for the armor_names, what is this used for? As we already have a way to convert the item stack name that hypixel shows in the museum gui to the museum set name. See here: https://github.com/NotEnoughUpdates/NotEnoughUpdates/blob/f4df7d2b6a4479415e879de8620740ae4471ed27/src/main/kotlin/io/github/moulberry/notenoughupdates/util/MuseumUtil.kt#L92

thank you hypixel.

**Comment by 7azeemm** [comment]
oh so its hypixel's fault,
maybe we can override data from api right? cuz looks like they not gonna fix it in any time soon

**Comment by NopoTheGamer** [comment]
You would have to hard code those values into the script that makes the file, editing the json yourself will just lose the changes when it finds more data

**Pull request closed without merging**
