### PR TITLE
water, dirt, fire, air

### PR DESCRIPTION
**Pull request by jani270**

### CODE REVIEW

**Comment by Futuremappermydud** [comment]
Where are the other chum items?

**Comment by jani270** [comment]
> Where are the other chum items?

I'm glad you ask, if you see missing items you can add them yourself with almost no effort! Instead of commenting on my pr that has been opened like 15min after the update. 🤡

**Comment by jani270** [comment]
> Where are the other chum items?

You can add them :)

**Comment by Futuremappermydud** [comment]
What is the process for adding items?

**Comment by jani270** [comment]
> What is the process for adding items?

You find them ingame, then you follow the instruction on the main page, then you upload them

**Review by Lulonaut — DISMISSED** [review]

**Comment by jani270** [comment]
> Looking good to me—too scared of jani to approve tho. And what's with the avatar reference?

Good that you dont have perms to approve

**Review by NopoTheGamer — APPROVED** [review]

**Review by Lulonaut — APPROVED** [review]

**Review by NopoTheGamer — APPROVED** [review]

**Pull request merged**
