### PR TITLE
Add Garden NPCs

### PR DESCRIPTION
**Pull request by romangraef**
Adds waypoints to most garden NPCs. Missing are: Sirius (because i dont wanna wait for a dark auction), Terry (because uhhhhh island closed), and all the crystal hollow NPCs. This took a total of 35 minutes, jani you are a pussy telling me this would be effort.

### CODE REVIEW

**Comment by kr45732** [comment]
recipes 
image

**Comment by romangraef** [comment]
@kr45732 wdym? these npcs do not have recipes, these are for waypoints. talking to these npcs unlocks them as customer in the garden.

**Comment by kr45732** [comment]
I mean for rusty, gwendolyn, and possibly a few others

**Comment by romangraef** [comment]
Thats out of scope for this pr, dm me a list of missing npc shops tho

**Review by jani270 — APPROVED** [review]
lgtm

**Review by NopoTheGamer — APPROVED** [review]

**Pull request merged**
