### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by SchIaumeyer**
Part 1/? Skyblock is down.

Are the power orbs correct like this?

### CODE REVIEW

**Comment by jani270** [comment]
> Are the power orbs correct like this?
No

**Comment by jani270** [comment]
> Are the power orbs correct like this?
No

**Comment by SchIaumeyer** [comment]
Whats wrong?

**Comment by jani270** [comment]
> Whats wrong?

You removed the recipes lol

**Comment by jani270** [comment]
And the slayer req and you forgot the wiki link for the skin

**Comment by SchIaumeyer** [comment]
but they work... like I can click on the item

**Comment by SchIaumeyer** [comment]
how does the slayer req even work? the lore and the slayer_req: line or?

**Comment by jani270** [comment]
> but they work... like I can click on the item

Restart your game and it will stop working

**Comment by jani270** [comment]
> how does the slayer req even work? the lore and the slayer_req: line or?

Normally the second thing is a check if the player can craft it (is broken I think but we should still add it) 
And lore is just for the people

**Comment by SchIaumeyer** [comment]
> > how does the slayer req even work? the lore and the slayer_req: line or?
> 
> Normally the second thing is a check if the player can craft it (is broken I think but we should still add it) And lore is just for the people

ok, so you have to manually add that, an implementation to the dev tool would be nice, if it even works

**Comment by jani270** [comment]
> > > how does the slayer req even work? the lore and the slayer_req: line or?
> > 
> > Normally the second thing is a check if the player can craft it (is broken I think but we should still add it) And lore is just for the people
> 
> ok, so you have to manually add that, an implementation to the dev tool would be nice, if it even works

If I dont forget it, I will add it to the board

**Review by jani270 — APPROVED** [review]

**Review by NopoTheGamer — APPROVED** [review]
ing

**Pull request merged**
